<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4379d100-911a-4d13-945c-75361ec52354</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GRPCClient\GRPCClient.csproj" />
    <ProjectReference Include="..\GRPCService\GRPCService.csproj" />
  </ItemGroup>

</Project>
