<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Microsoft.Extensions.Hosting provides the generic host, DI, configuration, and logging -->
    <PackageReference Include="Microsoft.Extensions.Hosting"  />
  </ItemGroup>

</Project>
