@APIErrorHandling_HostAddress = http://localhost:5275

@id = 2

### GET all books
GET {{APIErrorHandling_HostAddress}}/api/books
Accept: application/json

### GET book by id
GET {{APIErrorHandling_HostAddress}}/api/books/{{id}}
Accept: application/json

### Create a book

POST {{APIErrorHandling_HostAddress}}/api/books
Accept: application/json
Content-Type: application/json

{
  "title": "Pragmatic Microservices",
  "publisher": "Packt Publishing"
}

### Update a book

PUT {{APIErrorHandling_HostAddress}}/api/books/{{id}}
Accept: application/json
Content-Type: application/json

{
  "id": "{{id}}",
  "title": "Pragmatic Microservices with C# and Azure",
  "publisher": "Packt Publishing"
}

### Delete a book

DELETE {{APIErrorHandling_HostAddress}}/api/books/{{id}}
